import Head from "next/head";

import Layout from "../components/layout/Layout";
import Hero from "../components/Hero";
import HalfBlocks from "../components/common/HalfBlocks";
import Slider from "../components/Slider";
import Contact from "../components/Contact";
import PDFCards from "../components/common/PDFCards";

export default function Home() {
  return (
    <>
      <Head>
        <title>FRSEA AuRA</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <Hero></Hero>
        <HalfBlocks id='halfBlockA'>
          <PDFCards block='A' />
          <div className='half-blocks__image img-right'>
            <img src='/right.jfif' width='100%' />
          </div>
        </HalfBlocks>
        <Slider />
        <HalfBlocks id='halfBlockB'>
          <div className='half-blocks__image img-left'>
            <img src='/left.jpg' width='100%' />
          </div>
          <PDFCards block='B' />
        </HalfBlocks>
        <Contact />
      </Layout>
    </>
  );
}
